[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[build]
  publish = "build/"
  command = "CI=false yarn build"
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  minify = true
[build.processing.images]
  compress = true